# Generated by Django 2.0.3 on 2018-08-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='musics/track/img', verbose_name='фото'),
        ),
    ]
