# Generated by Django 2.0.3 on 2018-08-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_musictrack_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musictrack',
            name='image',
            field=models.ImageField(blank=True, default='/static/img/parallax-hero-3.jpg', null=True, upload_to='musics/track/img', verbose_name='фото'),
        ),
    ]
