# Generated by Django 2.0.3 on 2018-03-30 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_auto_20180329_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='image',
        ),
    ]
