# Generated by Django 2.0.3 on 2018-08-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_auto_20180824_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musictrack',
            name='image',
            field=models.ImageField(blank=True, default='/media/musics/track/img/logo1_icbvcAy.png', null=True, upload_to='musics/track/img', verbose_name='фото'),
        ),
    ]
