# Generated by Django 2.0.3 on 2018-08-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_auto_20180824_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musictrack',
            options={'ordering': ['reiting'], 'verbose_name': 'Музыка', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='image',
            field=models.ImageField(blank=True, default='musics/track/img/logo1.png', null=True, upload_to='musics/track/img', verbose_name='фото'),
        ),
    ]
