# Generated by Django 2.0.3 on 2018-04-02 08:28

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_remove_music_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(default=123123, upload_to='mu', verbose_name='фото'),
            preserve_default=False,
        ),
    ]
