# Generated by Django 2.0.3 on 2018-04-02 09:02

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_music_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='reiting',
            field=models.IntegerField(default=1, verbose_name='количество голосов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='musics', verbose_name='фото'),
        ),
    ]
