# Generated by Django 2.0.3 on 2018-08-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_auto_20180825_0506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musictrack',
            options={'ordering': ['-reiting'], 'verbose_name': 'Музыка', 'verbose_name_plural': 'Треки'},
        ),
    ]
