# Generated by Django 2.0.3 on 2018-04-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0006_auto_20180402_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['-reiting'], 'verbose_name': 'Музыка', 'verbose_name_plural': 'Музыка'},
        ),
        migrations.RemoveField(
            model_name='music',
            name='image',
        ),
        migrations.AlterField(
            model_name='music',
            name='reiting',
            field=models.IntegerField(blank=True, default=0, verbose_name='количество голосов'),
        ),
    ]
