# Generated by Django 2.0.3 on 2018-08-29 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0006_auto_20180825_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musictrack',
            name='music',
            field=models.FileField(upload_to='music/tracks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])], verbose_name='музыка'),
        ),
    ]
