# Generated by Django 2.0.3 on 2018-10-10 04:38

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0007_auto_20180829_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musictrack',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='musics/track/img/logo1.png', null=True, upload_to='musics/track/img', verbose_name='фото'),
        ),
    ]
