# Generated by Django 2.0.3 on 2018-05-21 08:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0008_auto_20180515_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, verbose_name='название категории')),
                ('slug', models.SlugField(blank=True, default=None, max_length=100, verbose_name='название ссылки категории')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='дата создание')),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='дата обнолвения')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='music',
            name='category',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='musics.Category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
