# Generated by Django 2.0.3 on 2018-05-24 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0009_auto_20180521_0816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='MusicClip',
        ),
    ]
