# Generated by Django 2.0.3 on 2018-05-24 06:41

import django.core.validators
from django.db import migrations, models
import musics.models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0011_auto_20180524_0449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musictrack',
            options={'ordering': ['sorted_list'], 'verbose_name': 'Музыка', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='music',
            field=models.FileField(upload_to=musics.models.get_music_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])], verbose_name='музыка'),
        ),
    ]
