# Generated by Django 2.0.3 on 2018-06-04 09:51

import django.core.validators
from django.db import migrations, models
import musics.models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0012_auto_20180524_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default=None, max_length=13, null=True, verbose_name='иконка'),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='music',
            field=models.FileField(upload_to=musics.models.get_music_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])], verbose_name='музыка'),
        ),
    ]
